CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(250) NOT NULL,
  email         VARCHAR(254) NOT NULL,
  CONSTRAINT    pk_user PRIMARY KEY (id),
  CONSTRAINT    UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat           FLOAT NOT NULL,
  lon           FLOAT NOT NULL,
  CONSTRAINT    pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                 VARCHAR(2000) NOT NULL,
  CONSTRAINT           pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation           VARCHAR(2000) NOT NULL,
  category_id          BIGINT NOT NULL,
  description          VARCHAR(7000) NOT NULL,
  event_date           TIMESTAMP NOT NULL,
  location_id          BIGINT NOT NULL,
  paid                 BOOLEAN DEFAULT FALSE,
  participant_limit    INT NOT NULL,
  request_moderation   BOOLEAN NOT NULL,
  title                VARCHAR(120) NOT NULL,
  confirmed_requests   BIGINT,
  created_on           TIMESTAMP NOT NULL,
  initiator            BIGINT NOT NULL,
  published_on         TIMESTAMP,
  state                smallint,
  views                BIGINT,
  CONSTRAINT           pk_event PRIMARY KEY (id),
  FOREIGN KEY          (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  FOREIGN KEY          (initiator) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY          (location_id) REFERENCES locations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created       TIMESTAMP(6) NOT NULL,
  event         BIGINT NOT NULL,
  requester     BIGINT NOT NULL,
  status        smallint,
  CONSTRAINT    pk_request PRIMARY KEY (id),
  FOREIGN KEY   (event) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY   (requester) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned         BOOLEAN,
  title          VARCHAR(255) NOT NULL,
  CONSTRAINT     pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
  compilation_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  PRIMARY KEY (compilation_id, event_id),
  FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_views (
    event_id BIGINT NOT NULL,
    ip VARCHAR(45) NOT NULL,
    viewed_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_event_view PRIMARY KEY (event_id, ip),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);