services:
  stats-server:
    build: ./stats/stats-server
    image: explore-with-me-stats-server
    container_name: explore-with-me-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=151200postgre

  stats-db:
    image: postgres:17
    container_name: explore-with-me-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=151200postgre
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service
    image: explore-with-me-ewm-service
    container_name: explore-with-me-ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=151200postgre
      - HIT_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:17
    container_name: explore-with-me-ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=151200postgre
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewmservice
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10